all/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

# @Author  : bianbian
# @Site    : 
# @File    : urls.py
# @Software: bianbian's PyCharm
# @Time    : 2017/12/21 15:14

from django.conf.urls import url
from . import views

app_name = 'all'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

cart/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

# @Author  : bianbian
# @Site    : Asia/Shanghai
# @File    : urls.py
# @Software: bianbian's PyCharm
# @Time    : 2018/1/2 18:05

from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^add/(?P<product_id>[-\w]+)$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>[-\w]+)$', views.cart_remove, name='cart_remove'),
    url(r'^$', views.cart_detail, name='cart_detail'),


]

myshop/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

# @Author  : bianbian
# @Site    : 
# @File    : urls.py
# @Software: bianbian's PyCharm
# @Time    : 2017/12/20 17:52

from django.conf.urls import url
from . import views

app_name = 'shop'

urlpatterns = [
    url(r'^category/(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^category/(?P<c_id>\d+)/product/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    url(r'^category/$', views.product_list, name='product_list'),

    url(r'^$', views.product_list, name='index'),

]

orders/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

# @Author  : bianbian
# @Site    : Asia/Shanghai
# @File    : urls.py
# @Software: bianbian's PyCharm
# @Time    : 2018/1/2 17:47

from django.conf.urls import url
from . import views


app_name = 'orders'

urlpatterns = [
   url(r'^create/$', views.order_create, name='order_create'),
]

pinhead/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from . import settings

urlpatterns = [

    ######  url for admin   #########
    url(r'^admin/', admin.site.urls),
    #################################

    ###### url for mycronjob #########
    url(r'^cronjob/', include('mycronjob.urls')),
    ###################################

    ####### url for key_value #########
    url(r'^keyvalue/', include('key_value.urls')),
    #######################################

    ######## url for ess ################
    url(r'^ess/', include('ess.urls')),
    #####################################

    ######## url for myshop-cart ################
    url(r'^cart/', include('cart.urls', namespace='cart')),
    #####################################

    ######## url for myshop-orders ################
    # url(r'^shop/', include('myshop.urls', namespace='myshop')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    #####################################

    ######## url for myshop ################
    # url(r'^shop/', include('myshop.urls', namespace='myshop')),
    url(r'^shop/', include('myshop.urls')),
    #####################################

    ######## url for pagetest ################
    url(r'^pagetest/', include('pagetest.urls')),
    #####################################

    ######## url for restapp ################
    url(r'^restapp/', include('restapp.urls')),
    #####################################

    ######## url for filetrans ################
    url(r'^filetrans/', include('filetrans.urls')),
    #####################################

    #######  url for all   ##########
    url(r'^', include('all.urls')),
    #################################

    #######  url for myuser   ##########
    url(r'^myuser/', include('myuser.urls.views_urls')),
    # url(r'^api/myuser/', include('myuser.urls.api_urls')),
    #################################

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))

]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
#                + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

cart/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

# @Author  : bianbian
# @Site    : Asia/Shanghai
# @File    : forms.py
# @Software: bianbian's PyCharm
# @Time    : 2018/1/2 14:39

from django import forms

PRODOCT_QUANTITY_CHOIDCES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODOCT_QUANTITY_CHOIDCES,
        coerce=int
    )
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST

from .cart import Cart
from .forms import CartAddProductForm

import sys
sys.path.append("..")
from myshop.models import Category, Product


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        # print('request form data: ' + str(cd))
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product=product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'],
                     'update': True}
        )
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "myshop/base.html" %}
{% load static %}

{% block title %}
    Your shopping cart
{% endblock %}

{% block content %}
<h1>Your shopping cart</h1>
<table class="cart">
    <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
    {% for item in cart %}
        {% with product=item.product %}
            <tr>
                <td>
                    <a href="{{product.get_absolute_url}}">
                        <!--![]({% if product.image %}{{product.image.url}}{% else %}{% static 'no-image.jpg' %}{% endif %})-->
                        <!--<img src="{% if product.image %}{{product.image.url}}{% else %}{% static 'no-image.jpg' %}{% endif %}" width="20" height="20">-->
                        <!-- static: will looking from myshop/static first, so no-image.jpg will load from myshop/static/no-image.jpg -->
                        <img src="{% if product.image %}{{product.image.url}}{% else %}{% static 'no-image2.jpg' %}{% endif %}" width="20" height="20">
                    </a>
                </td>
                <td>{{product.name}}</td>
                <!--<td>{{item.quantity}}</td>-->
                <td>
                    <form action="{% url 'cart:cart_add' product.id %}" method="post">
                        {{item.update_quantity_form.quantity}}
                        {{item.update_quantity_form.update}}
                        <input type="submit" value="update"/>
                        {% csrf_token %}
                    </form>
                </td>
                <td><a href="{% url 'cart:cart_remove' product.id %}">Remove</a></td>
                <td class="num">${{item.price}}</td>
                <td class="num">${{item.total_price}}</td>
            </tr>
        {% endwith %}
    {% endfor %}
    <tr class="total">total price: {{cart.get_total_price}}</tr>
    </tbody>
</table>
<p class="text-right">
    <a href="{% url 'shop:product_list' %}" class="button light">Continue shopping</a>
    <a href="{% url 'orders:order_create' %}" class="button">Checkout</a>
</p>
{% endblock %}