all/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

# @Author  : bianbian
# @Site    : 
# @File    : urls.py
# @Software: bianbian's PyCharm
# @Time    : 2017/12/21 15:14

from django.conf.urls import url
from . import views

app_name = 'all'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

filetrans/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

# @Author  : bianbian
# @Site    : Asia/Shanghai
# @File    : urls.py
# @Software: bianbian's PyCharm
# @Time    : 2018/7/2 15:05

from django.conf.urls import url

from filetrans import views

app_name = 'filetrans'

urlpatterns = [
    url(r'^$', views.upload_accept, name='upload-accept'),
    url(r'^upload/accept$', views.upload_accept, name='upload-accept'),
    url(r'^upload/complete$', views.upload_complete, name='upload-complete'),
]

pinhead/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from . import settings

urlpatterns = [

    ######  url for admin   #########
    url(r'^admin/', admin.site.urls),
    #################################

    ###### url for mycronjob #########
    url(r'^cronjob/', include('mycronjob.urls')),
    ###################################

    ####### url for key_value #########
    url(r'^keyvalue/', include('key_value.urls')),
    #######################################

    ######## url for ess ################
    url(r'^ess/', include('ess.urls')),
    #####################################

    ######## url for myshop-cart ################
    url(r'^cart/', include('cart.urls', namespace='cart')),
    #####################################

    ######## url for myshop-orders ################
    # url(r'^shop/', include('myshop.urls', namespace='myshop')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    #####################################

    ######## url for myshop ################
    # url(r'^shop/', include('myshop.urls', namespace='myshop')),
    url(r'^shop/', include('myshop.urls')),
    #####################################

    ######## url for pagetest ################
    url(r'^pagetest/', include('pagetest.urls')),
    #####################################

    ######## url for restapp ################
    url(r'^restapp/', include('restapp.urls')),
    #####################################

    ######## url for filetrans ################
    url(r'^filetrans/', include('filetrans.urls')),
    #####################################

    #######  url for all   ##########
    url(r'^', include('all.urls')),
    #################################

    #######  url for myuser   ##########
    url(r'^myuser/', include('myuser.urls.views_urls')),
    # url(r'^api/myuser/', include('myuser.urls.api_urls')),
    #################################

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))

]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
#                + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

filetrans/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

filetrans/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os

from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt


@csrf_exempt
def upload_accept(request):
    if request.method == 'POST':
        upload_file = request.FILES['file']
        task = request.POST.get('task_id')  # 获取文件唯一标识符
        chunk = request.POST.get('chunk', 0)  # 获取该分片在所有分片中的序号
        filename = '%s%s' % (task, chunk)  # 构成该分片唯一标识符
        file_full_name = 'media/filetrans/upload/%s' % filename
        try:
            os.makedirs(os.path.dirname(file_full_name))
        except OSError:
            pass
        with open(file_full_name, 'wb') as f:
            for chunk in upload_file.chunks():
                f.write(chunk)  # 保存分片到本地
    context = {}
    return render(request, 'filetrans/index.html', context=context)


# @csrf_exempt
def upload_complete(request):  # 所有分片均上传完后被调用
    target_filename = request.GET.get('filename')  # 获取上传文件的文件名
    task = request.GET.get('task_id')  # 获取文件的唯一标识符
    chunk = 0  # 分片序号
    with open('media/filetrans/upload/%s' % target_filename, 'wb') as target_file:  # 创建新文件
        while True:
            try:
                filename = 'media/filetrans/upload/%s%d' % (task, chunk)
                source_file = open(filename, 'rb')  # 按序打开每个分片
                target_file.write(source_file.read())  # 读取分片内容写入新文件
                source_file.close()
            except IOError:
                break
            chunk += 1
            os.remove(filename)  # 删除该分片，节约空间
    context = {}
    return render(request, 'filetrans/index.html', context=context)

filetrans/templates/filetrans/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>文件分片上传</title>
    <script src="{% static 'js/jquery-2.1.1.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'wu/webuploader.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'wu/webuploader.css' %}"/>
</head>

<body>
<div>
    <div id="picker">请选择</div>   <!-- 上传按钮，必须指定id选择器的值 -->
    <div class="progress">         <!-- 进度条 -->
        <div class="progress-bar progress-bar-striped active" role="progressbar" style="width:0%;"></div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        var task_id = WebUploader.Base.guid();        //产生task_id
        var uploader = WebUploader.create({           //创建上传控件
            swf: "{% static 'wu/Uploader.swf' %}", //swf位置，这个可能与flash有关
            server: "{% url 'filetrans:upload-accept' %}",                 //接收每一个分片的服务器地址
            pick: '#picker',                          //填上传按钮的id选择器值
            auto: true,                               //选择文件后，是否自动上传
            chunked: true,                            //是否分片
            chunkSize: 20 * 1024 * 1024,              //每个分片的大小，这里为20M
            chunkRetry: 3,                            //某分片若上传失败，重试次数
            threads: 1,                               //线程数量，考虑到服务器，这里就选了1
            duplicate: true,                          //分片是否自动去重
            formData: {                               //每次上传分片，一起携带的数据
                task_id: task_id,
            },
        });

        uploader.on('startUpload', function () {       //开始上传时，调用该方法
            $('.progress-bar').css('width', '0%');
            $('.progress-bar').text('0%');
        });

        uploader.on('uploadProgress', function (file, percentage) { //一个分片上传成功后，调用该方法
            $('.progress-bar').css('width', percentage * 100 - 1 + '%');
            $('.progress-bar').text(Math.floor(percentage * 100 - 1) + '%');
        });

        uploader.on('uploadSuccess', function (file) { //整个文件的所有分片都上传成功，调用该方法
            //上传的信息（文件唯一标识符，文件名）
            var data = {'task_id': task_id, 'filename': file.source['name']};
            $.get("{% url 'filetrans:upload-complete' %}", data);          //ajax携带data向该url发请求
            $('.progress-bar').css('width', '100%');
            $('.progress-bar').text('上传完成');
        });

        uploader.on('uploadError', function (file) {   //上传过程中发生异常，调用该方法
            $('.progress-bar').css('width', '100%');
            $('.progress-bar').text('上传失败');
        });

        uploader.on('uploadComplete', function (file) {//上传结束，无论文件最终是否上传成功，该方法都会被调用
            $('.progress-bar').removeClass('active progress-bar-striped');
        });

    });
</script>
</body>


</html>